---
#nginx_version: nginx-1.21.0
nginx_url: https://nginx.org/download/{{ nginx_version }}.tar.gz
#nginx_root_dir: /usr/local/nginx
#nginx_log_dir: /data/logs/nginx
#nginx_pid_dir: /var/run/nginx
nginx_global_dir: "{{ nginx_root_dir }}/global"
nginx_vhost_dir: "{{ nginx_root_dir }}/conf/vhost"