- name: Install nginx
  hosts: c7-web
  vars:
    nginx_version: nginx-1.21.0
    nginx_root_dir: /usr/local/nginx
    nginx_log_dir: /data/logs/nginx
    nginx_pid_file: /var/run/nginx.pid
  roles:
    - nginx