---
- name: Install php
  remote_user: root
  hosts: c7-web
  vars:
    php_version: php-7.2.34
    php_url: https://www.php.net/distributions/{{ php_version }}.tar.gz
    php_root_dir: /usr/local/php/72
    php_service: php72-fpm
    php_sock_file: "/dev/shm/php72-fpm.sock"
    php_error_log_file: "{{ php_log_dir }}/php72-fpm.log"
    php_slow_log_file: "{{ php_log_dir }}/php72-slow.log"
    redis_version: redis-5.3.7
    imagick_version: imagick-3.5.1
  roles:
    - php